In [1]:
list1 =  ['jong','David','Jeff','Jun']
print(list1[0])

jong


In [3]:
import numpy as np

In [5]:
arr1 = np.random.rand(8)
# this will create random number from [0-1[
print(arr1)

[0.69461879 0.80478675 0.8373078  0.50272286 0.55253527 0.38126637
 0.52258544 0.67652704]


#Indexing and Selection

In [6]:
arr1[0]

np.float64(0.6946187913669277)

In [7]:
arr1[-1]# this will print the last number in the array

np.float64(0.6765270406418976)

# slicing

In [8]:
arr1

array([0.69461879, 0.80478675, 0.8373078 , 0.50272286, 0.55253527,
       0.38126637, 0.52258544, 0.67652704])

In [9]:
print(arr1[1:4])

[0.80478675 0.8373078  0.50272286]


In [10]:
print(arr1[1:])

[0.80478675 0.8373078  0.50272286 0.55253527 0.38126637 0.52258544
 0.67652704]


In [11]:
print(arr1[:4])

[0.69461879 0.80478675 0.8373078  0.50272286]


# 2d Array Indexing



*   1d list >> only rows
*   2d list >> rows plus column



In [15]:
list_1d = [1,2,3,4,5,6,7,8,9]
list2d = [[1,2,3],
          [4,5,6],
          [7,8,9]]
print(list2d[1][1]) #first box is for row, the second one is for column
print(list2d[1][2])


5
6


In [17]:
list_2d = [[10,20,30], [40,50,60],[70,80,90]]
arr1 = np.array(list_2d)
print(arr1)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
# [][]
# [,] > [Row, column]

In [18]:
print(arr1[0])

[10 20 30]


In [20]:
print(arr1[1,1])
print(arr1[2,2])

50
90


In [21]:
print(arr1[0:2])

[[10 20 30]
 [40 50 60]]


In [22]:
print(arr1[0:2,0:2])

[[10 20]
 [40 50]]


<img src="https://i.ibb.co/jzPNtbq/Whats-App-Image-2024-06-16-at-20-44-41-cd8e9add.jpg" alt="Whats-App-Image-2024-06-16-at-20-44-41-cd8e9add" border="0" width="180">

In [25]:
import numpy as np
arr = np.array([
    [0, 1, 2, 3, 4, 5],
    [10, 11, 12, 13, 14, 15],
    [20, 21, 22, 23, 24, 25],
    [30, 31, 32, 33, 34, 35],
    [40, 41, 42, 43, 44, 45],
    [50, 51, 52, 53, 54, 55],
])

In [29]:
#orange
print(arr[0,3:5])

[3 4]


In [32]:
# red
print(arr[:,2])

[ 2 12 22 32 42 52]


In [34]:
# Blue
print(arr[4:,4:])

[[44 45]
 [54 55]]


In [38]:
#green "::2"
print(arr[2::2,::2])

[[20 22 24]
 [40 42 44]]
