<a href="https://colab.research.google.com/github/jong71/cod1/blob/main/numpybasics_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# numpy it is a library about python list (but with more functionalites)
# Limitation of a normal python list--> add,remove, update, check lenght
# we can solve this issues with Numpy Array
# "import" keyword --> use a library
# "as" keyword --> "alias"(a shortcut variable)
import numpy as np

#1.1 numpy arrays
1 .array()
2.List item()
3. arange()
4. zero and ones()
5. linspace


In [ ]:
# 1. Array()
# array() transforsm a normal list into numpy array
list1  = [1,22,45]
print(list1)
print(type(list1))

[1, 22, 45]
<class 'list'>


In [ ]:
array1 = np.array(list1)
print(array1)
print(type(array1))

[ 1 22 45]
<class 'numpy.ndarray'>


In [ ]:
# Arange()
# 2 input --> star, stop(exluding stop)
# [start,stop)
# [0,10)
# [] inclusive
# () exlusive
arr2 = np.arange(0,10)
print(arr2 )
arr3 = np.arange(0,100,5)
print(arr3)


[0 1 2 3 4 5 6 7 8 9]
[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [ ]:
# Zeros and ones
arr8 = np.zeros(10)
print(arr8)
arr9 = np.ones(10)
arr10 = np.ones((2,5)) #2 rows and 7 columns
print(arr9)
print(arr10)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# linspace - leanear spacing
#[start, stop]
# 1st input = "input"
#2nd input = "stop"INCLUDED
# 3rd input = "how many evenly spaced out numbers"
arr11 = np.linspace(0,5,100)
print(arr11)

[0.         0.05050505 0.1010101  0.15151515 0.2020202  0.25252525
 0.3030303  0.35353535 0.4040404  0.45454545 0.50505051 0.55555556
 0.60606061 0.65656566 0.70707071 0.75757576 0.80808081 0.85858586
 0.90909091 0.95959596 1.01010101 1.06060606 1.11111111 1.16161616
 1.21212121 1.26262626 1.31313131 1.36363636 1.41414141 1.46464646
 1.51515152 1.56565657 1.61616162 1.66666667 1.71717172 1.76767677
 1.81818182 1.86868687 1.91919192 1.96969697 2.02020202 2.07070707
 2.12121212 2.17171717 2.22222222 2.27272727 2.32323232 2.37373737
 2.42424242 2.47474747 2.52525253 2.57575758 2.62626263 2.67676768
 2.72727273 2.77777778 2.82828283 2.87878788 2.92929293 2.97979798
 3.03030303 3.08080808 3.13131313 3.18181818 3.23232323 3.28282828
 3.33333333 3.38383838 3.43434343 3.48484848 3.53535354 3.58585859
 3.63636364 3.68686869 3.73737374 3.78787879 3.83838384 3.88888889
 3.93939394 3.98989899 4.04040404 4.09090909 4.14141414 4.19191919
 4.24242424 4.29292929 4.34343434 4.39393939 4.44444444 4.4949

In [ ]:
#create a simple array
# rand()--> create a random number for [0-1)
# rand()--> create a random number from [0-100)
arr1 = np.random.randint(10,100,33)
print(arr1.reshape(3,11))

print('---')
print(arr1.reshape(11,3).shape)

print('---')




[[44 90 75 85 17 47 98 96 11 36 25]
 [84 44 66 20 43 63 72 29 65 80 18]
 [90 21 53 99 97 88 33 47 61 42 81]]
---
(11, 3)
---


Bracket indexing and selection

In [ ]:
print(arr[0]) #indexing one element in the array
print(arr[-1])

0.5917896654555638
0.05210114720379344


In [ ]:
#Slicing
print(arr[1:6])

[0.76300509 0.10061511 0.05933306 0.34043325 0.27052214]


2D Array indexing

In [ ]:
#normal python list

# 1st number - row
# 2nd number - column

list_1d = [1,2,3,4,5,6,7,8,9]
list_2d = [[1,2,3],
           [4,5,6],
           [7,8,9]]

print(list_2d[1])
print(list_2d[1][1]) # row 2 , column 2 --> row index 1, column index 1

print('---')
print(list_2d[-1])
print(list_2d[-1][-1])

[4, 5, 6]
5
---
[7, 8, 9]
9


In [ ]:
list_2d = [[10,20,30],[40,50,60],[70,80,90]] #let's convert it into a numpy array
arr_2d = np.array(list_2d)
print(list_2d)
print(arr_2d)

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
# in numpy in order to index or slice an array u can use [x,y] instead [x][y]
# 2. [ , ] notation
print(arr_2d[0])
print(arr_2d[2,0])
print(arr_2d[2,2])
print(arr_2d[2,-1])

[10 20 30]
70
90
90


2D ARRAY SLICING

In [ ]:
list1 = [[10,58,56],
         [55,66,90],
         [89,48,70]]
arr2 = np.array(list1)
print(arr2)

[[10 58 56]
 [55 66 90]
 [89 48 70]]


In [ ]:
print(list1[1:])# normal

[[55, 66, 90], [89, 48, 70]]


In [ ]:
print(arr2[0:2])
print('----')
print(arr2[1:])

[[10 58 56]
 [55 66 90]]
----
[[55 66 90]
 [89 48 70]]


In [ ]:
print(arr2)

[[10 58 56]
 [55 66 90]
 [89 48 70]]


In [ ]:
# example 2
print(arr2[1:3,1:3])
print('---')
print(arr2[1:,1:]) # shortcut

[[66 90]
 [48 70]]
---
[[66 90]
 [48 70]]


In [ ]:
print(arr2)

[[10 58 56]
 [55 66 90]
 [89 48 70]]


In [ ]:
print(arr2[0:3,1].reshape(3,1))

[[58]
 [66]
 [48]]


In [ ]:
print(arr2[0:3,:1])

[[10]
 [55]
 [89]]


In [ ]:
arr20 = np.array([33,444,898,666,777,884,514])
print(arr20)
print(arr20[2:5])

[ 33 444 898 666 777 884 514]
[898 666 777]
